// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pos.Infrastructure.Persistence;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260606195127_ProductUniqueIndexesPerTenant")]
    partial class ProductUniqueIndexesPerTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pos.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<int>("TaxClass")
                        .HasColumnType("integer")
                        .HasColumnName("tax_class");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("integer")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ux_products_tenant_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_products_tenant_sku");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityDelta")
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity_delta");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("SourceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StoreId", "ProductId")
                        .HasDatabaseName("ix_stock_movements_tenant_store_product");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Payments.MpesaPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckoutRequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checkout_request_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("InitiatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("initiated_at_utc");

                    b.Property<string>("MerchantRequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("merchant_request_id");

                    b.Property<string>("MpesaReceiptNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mpesa_receipt");

                    b.Property<string>("MsisdnMasked")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("msisdn_masked");

                    b.Property<int?>("ResultCode")
                        .HasColumnType("integer")
                        .HasColumnName("result_code");

                    b.Property<string>("ResultDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("result_description");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("tender_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_mpesa_checkout_request_id");

                    b.HasIndex("TenantId", "StoreId", "SaleId")
                        .HasDatabaseName("ix_mpesa_tenant_store_sale");

                    b.ToTable("mpesa_payments", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("EtimsCuin")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etims_cuin");

                    b.Property<string>("EtimsQrUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("etims_qr_url");

                    b.Property<string>("EtimsSignature")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("etims_signature");

                    b.Property<DateTimeOffset?>("EtimsSignedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("etims_signed_at_utc");

                    b.Property<DateTimeOffset?>("EtimsTransmittedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("etims_transmitted_at_utc");

                    b.Property<int>("FiscalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_status");

                    b.Property<int>("FiscalSyncAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_sync_attempts");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("receipt_number");

                    b.Property<Guid>("RegisterId")
                        .HasColumnType("uuid")
                        .HasColumnName("register_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StoreId", "Id")
                        .HasDatabaseName("ix_sales_tenant_store_id");

                    b.HasIndex("TenantId", "StoreId", "Status")
                        .HasDatabaseName("ix_sales_tenant_store_status");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("EnqueuedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("enqueued_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StoreId", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Persistence.ReceiptCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.HasKey("TenantId", "StoreId");

                    b.ToTable("receipt_counters", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Catalog.Product", b =>
                {
                    b.OwnsOne("Pos.SharedKernel.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Payments.MpesaPayment", b =>
                {
                    b.OwnsOne("Pos.SharedKernel.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("MpesaPaymentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("MpesaPaymentId");

                            b1.ToTable("mpesa_payments");

                            b1.WithOwner()
                                .HasForeignKey("MpesaPaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.OwnsOne("Pos.SharedKernel.Money", "GrandTotal", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("grand_total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("grand_total_currency");

                            b1.HasKey("SaleId");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsMany("Pos.Domain.Sales.SaleLine", "_lines", b1 =>
                        {
                            b1.Property<Guid>("sale_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity");

                            b1.Property<int>("TaxClass")
                                .HasColumnType("integer")
                                .HasColumnName("tax_class");

                            b1.Property<int>("UnitOfMeasure")
                                .HasColumnType("integer")
                                .HasColumnName("unit_of_measure");

                            b1.HasKey("sale_id", "Id");

                            b1.ToTable("sale_lines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("sale_id");

                            b1.OwnsOne("Pos.SharedKernel.Money", "TaxableAmount", b2 =>
                                {
                                    b2.Property<Guid>("SaleLinesale_id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SaleLineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxable_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("taxable_currency");

                                    b2.HasKey("SaleLinesale_id", "SaleLineId");

                                    b2.ToTable("sale_lines");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleLinesale_id", "SaleLineId");
                                });

                            b1.OwnsOne("Pos.SharedKernel.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("SaleLinesale_id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SaleLineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("unit_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("unit_price_currency");

                                    b2.HasKey("SaleLinesale_id", "SaleLineId");

                                    b2.ToTable("sale_lines");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleLinesale_id", "SaleLineId");
                                });

                            b1.OwnsOne("Pos.SharedKernel.Money", "VatAmount", b2 =>
                                {
                                    b2.Property<Guid>("SaleLinesale_id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SaleLineId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("vat_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("vat_currency");

                                    b2.HasKey("SaleLinesale_id", "SaleLineId");

                                    b2.ToTable("sale_lines");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleLinesale_id", "SaleLineId");
                                });

                            b1.Navigation("TaxableAmount")
                                .IsRequired();

                            b1.Navigation("UnitPrice")
                                .IsRequired();

                            b1.Navigation("VatAmount")
                                .IsRequired();
                        });

                    b.OwnsMany("Pos.Domain.Sales.SaleVatSummaryLine", "_vatSummary", b1 =>
                        {
                            b1.Property<Guid>("sale_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("TaxClass")
                                .HasColumnType("integer")
                                .HasColumnName("tax_class");

                            b1.HasKey("sale_id", "TaxClass");

                            b1.ToTable("sale_vat_summary", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("sale_id");

                            b1.OwnsOne("Pos.SharedKernel.Money", "TaxableAmount", b2 =>
                                {
                                    b2.Property<Guid>("SaleVatSummaryLinesale_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("SaleVatSummaryLineTaxClass")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("taxable_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("taxable_currency");

                                    b2.HasKey("SaleVatSummaryLinesale_id", "SaleVatSummaryLineTaxClass");

                                    b2.ToTable("sale_vat_summary");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleVatSummaryLinesale_id", "SaleVatSummaryLineTaxClass");
                                });

                            b1.OwnsOne("Pos.SharedKernel.Money", "VatAmount", b2 =>
                                {
                                    b2.Property<Guid>("SaleVatSummaryLinesale_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("SaleVatSummaryLineTaxClass")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("vat_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("vat_currency");

                                    b2.HasKey("SaleVatSummaryLinesale_id", "SaleVatSummaryLineTaxClass");

                                    b2.ToTable("sale_vat_summary");

                                    b2.WithOwner()
                                        .HasForeignKey("SaleVatSummaryLinesale_id", "SaleVatSummaryLineTaxClass");
                                });

                            b1.Navigation("TaxableAmount")
                                .IsRequired();

                            b1.Navigation("VatAmount")
                                .IsRequired();
                        });

                    b.OwnsMany("Pos.Domain.Sales.Tender", "_tenders", b1 =>
                        {
                            b1.Property<Guid>("sale_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ProviderReference")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("provider_reference");

                            b1.Property<string>("Reference")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("reference");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("sale_id", "Id");

                            b1.ToTable("tenders", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("sale_id");

                            b1.OwnsOne("Pos.SharedKernel.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("Tendersale_id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("TenderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("Tendersale_id", "TenderId");

                                    b2.ToTable("tenders");

                                    b2.WithOwner()
                                        .HasForeignKey("Tendersale_id", "TenderId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("GrandTotal")
                        .IsRequired();

                    b.Navigation("_lines");

                    b.Navigation("_tenders");

                    b.Navigation("_vatSummary");
                });
#pragma warning restore 612, 618
        }
    }
}
